name: Run tests on pull request
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - '*'
jobs:
  run-tests-job:
    runs-on: ubuntu-latest
    steps:
      - name: Start Selenoid
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.2
          args: -limit 10
          browsers: chrome;firefox
          last-versions: 1
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Run tests
        run: mvn clean test -Dmode=remote
      - name: Generate Allure report
        if: always()
        run: mvn allure:report
      - name: Deploy Allure report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: target/allure-report